version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
    groups:
      maven-minor-patch:
        update-types: [ minor, patch ]
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        update-types: [ version-update:semver-major, version-update:semver-minor ]

  - package-ecosystem: npm
    directory: /frontend
    target-branch: develop
    schedule:
      interval: monthly
    groups:
      npm-minor-patch:
        update-types: [ minor, patch ]

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: [ "*" ]

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
    groups:
      docker-minor-patch:
        update-types: [ minor, patch ]
    ignore:
      - dependency-name: maven
        update-types: [ version-update:semver-major ]

  - package-ecosystem: docker-compose
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
    groups:
      compose-minor-patch:
        update-types: [ minor, patch ]
    ignore:
      - dependency-name: postgres
        update-types: [ version-update:semver-major ]
