services:
  postgres:
    image: postgres:18.6-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=workbit_dev_db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1