spring:
  sql:
    init:
      mode: always
  datasource:
    username: dev
    password: dev
    url: jdbc:postgresql://localhost:5432/workbit_dev_db

management:
  endpoints:
    web:
      exposure:
        include: "*"