spring:
  sql:
    init:
      mode: always
  datasource:
    username: dev
    password: dev
    url: jdbc:postgresql://localhost:5432/workbit_dev_db
  mail:
    properties:
      mail.smtp.ssl.trust: "*"

jwt:
  secret: test-secret-key-not-used-in-production-123
  expiration: 3600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"