TRUNCATE interview.question_bank;

INSERT INTO interview.question_bank (category, level, text) VALUES
('JAVA_CORE', 'JUNIOR', 'Чем ArrayList отличается от LinkedList по сложности основных операций и когда что выбирать?'),
('JAVA_CORE', 'JUNIOR', 'Чем отличаются String, StringBuilder и StringBuffer, что такое пул строк?'),
('JAVA_CORE', 'MIDDLE', 'Чем отличается checked-исключение от unchecked? Когда оправдано использовать каждое?'),
('JAVA_CORE', 'MIDDLE', 'Какой контракт связывает equals() и hashCode() и что сломается при его нарушении?'),
('JAVA_CORE', 'MIDDLE', 'Что такое immutable-объект, какие шаги нужны, чтобы класс был по-настоящему неизменяемым?'),
('JAVA_CORE', 'MIDDLE', 'В чём смысл Optional и какие способы его применения считаются антипаттернами?'),
('JAVA_CORE', 'SENIOR', 'Как работает сборщик мусора и что такое утечка памяти в Java, если GC автоматический?'),
('JAVA_CORE', 'SENIOR', 'Зачем нужны generics и что такое type erasure? К каким ограничениям он приводит?'),

('CONCURRENCY', 'MIDDLE', 'Что делает ключевое слово volatile и какие проблемы оно не решает?'),
('CONCURRENCY', 'MIDDLE', 'Чем synchronized отличается от ReentrantLock? Какие возможности даёт второй?'),
('CONCURRENCY', 'MIDDLE', 'Что такое deadlock, приведите пример и способы его предотвращения.'),
('CONCURRENCY', 'MIDDLE', 'Для чего нужен CompletableFuture и чем он удобнее обычного Future?'),
('CONCURRENCY', 'SENIOR', 'Что гарантирует отношение happens-before и зачем оно нужно в Java Memory Model?'),
('CONCURRENCY', 'SENIOR', 'Как устроен ThreadPoolExecutor: что происходит при заполнении очереди и пула?'),
('CONCURRENCY', 'SENIOR', 'Как ConcurrentHashMap обеспечивает потокобезопасность без блокировки всей структуры?'),
('CONCURRENCY', 'SENIOR', 'Что такое CAS и как на нём построены классы из java.util.concurrent.atomic?'),

('SPRING', 'JUNIOR', 'Что такое IoC и Dependency Injection? Какие виды внедрения зависимостей предпочтительны и почему?'),
('SPRING', 'JUNIOR', 'Чем @Component, @Service, @Repository отличаются друг от друга, кроме семантики?'),
('SPRING', 'MIDDLE', 'Опишите жизненный цикл бина: основные фазы от создания до уничтожения.'),
('SPRING', 'MIDDLE', 'Что такое AOP в Spring и какие задачи им удобно решать?'),
('SPRING', 'MIDDLE', 'Как работает @Qualifier и @Primary при наличии нескольких кандидатов на инъекцию?'),
('SPRING', 'SENIOR', 'Какие бывают scope у бинов и в чём опасность инъекции prototype-бина в singleton?'),
('SPRING', 'SENIOR', 'Почему @Transactional не срабатывает при вызове метода внутри того же класса (self-invocation)?'),
('SPRING', 'SENIOR', 'Как Spring создаёт прокси для бинов и чем отличается JDK-прокси от CGLIB?'),

('SPRING_BOOT', 'JUNIOR', 'Что такое starter-зависимость и что она привносит в проект?'),
('SPRING_BOOT', 'MIDDLE', 'Как устроены профили (profiles) и как переключать конфигурацию между средами?'),
('SPRING_BOOT', 'MIDDLE', 'Зачем нужен Actuator и какие эндпоинты вы используете для мониторинга?'),
('SPRING_BOOT', 'MIDDLE', 'Как привязать группу настроек к классу через @ConfigurationProperties и чем это лучше @Value?'),
('SPRING_BOOT', 'MIDDLE', 'Чем отличается ddl-auto: validate от update и почему validate безопаснее для прода?'),
('SPRING_BOOT', 'SENIOR', 'Как работает автоконфигурация в Spring Boot и как её отключить или переопределить?'),
('SPRING_BOOT', 'SENIOR', 'Каков приоритет источников конфигурации в Spring Boot (properties, env, аргументы)?'),
('SPRING_BOOT', 'SENIOR', 'Как Spring Boot встраивает веб-сервер и как поменять Tomcat на другой контейнер?'),

('SQL_JPA', 'MIDDLE', 'Что такое проблема N+1 запросов в JPA, как её обнаружить и устранить?'),
('SQL_JPA', 'MIDDLE', 'Чем отличаются стратегии загрузки LAZY и EAGER и какие риски у каждой?'),
('SQL_JPA', 'MIDDLE', 'В чём разница между JPQL и нативным SQL? Когда оправдан нативный запрос?'),
('SQL_JPA', 'MIDDLE', 'Зачем нужны индексы в БД и почему они могут замедлять запись?'),
('SQL_JPA', 'SENIOR', 'Опишите состояния сущности в JPA (transient, managed, detached, removed).'),
('SQL_JPA', 'SENIOR', 'Что делает метод flush() и когда persistence context синхронизируется с БД?'),
('SQL_JPA', 'SENIOR', 'Чем отличается JOIN FETCH от обычного JOIN в JPQL?'),
('SQL_JPA', 'SENIOR', 'Что такое оптимистическая блокировка через @Version и какую проблему она решает?'),

('TRANSACTIONS', 'JUNIOR', 'Что означают свойства ACID и за что отвечает каждое из них?'),
('TRANSACTIONS', 'MIDDLE', 'При каких исключениях @Transactional делает rollback по умолчанию и как это изменить?'),
('TRANSACTIONS', 'MIDDLE', 'Что такое dirty read, non-repeatable read и phantom read?'),
('TRANSACTIONS', 'MIDDLE', 'Почему долгие транзакции опасны и как сократить их длительность?'),
('TRANSACTIONS', 'SENIOR', 'Какие уровни изоляции транзакций существуют и от каких аномалий они защищают?'),
('TRANSACTIONS', 'SENIOR', 'Что такое propagation в Spring и чем REQUIRED отличается от REQUIRES_NEW?'),
('TRANSACTIONS', 'SENIOR', 'Чем отличается оптимистическая блокировка от пессимистической? Когда что применять?'),
('TRANSACTIONS', 'LEAD', 'Как обеспечить согласованность данных между несколькими сервисами без распределённой транзакции?'),

('XML_SOAP', 'JUNIOR', 'Зачем нужны пространства имён (namespaces) в XML и как они разрешают конфликты?'),
('XML_SOAP', 'JUNIOR', 'Что входит в SOAP-конверт: header, body, fault — за что отвечает каждый элемент?'),
('XML_SOAP', 'MIDDLE', 'Чем SOAP отличается от REST и в каких случаях SOAP всё ещё предпочтителен?'),
('XML_SOAP', 'MIDDLE', 'Что описывает WSDL и из каких основных элементов он состоит?'),
('XML_SOAP', 'MIDDLE', 'Как в Java выполняется маршалинг и демаршалинг XML через JAXB?'),
('XML_SOAP', 'MIDDLE', 'Что такое XSD-схема и как она используется для валидации XML-документа?'),
('XML_SOAP', 'SENIOR', 'Чем отличается DOM-парсинг от SAX и StAX по потреблению памяти?'),
('XML_SOAP', 'SENIOR', 'Как обеспечивается безопасность в SOAP-сервисах (WS-Security)?'),

('LEGACY_INTEGRATION', 'MIDDLE', 'Как обеспечить обратную совместимость API при изменении контракта?'),
('LEGACY_INTEGRATION', 'MIDDLE', 'Как покрыть тестами legacy-код, который писался без оглядки на тестируемость?'),
('LEGACY_INTEGRATION', 'MIDDLE', 'Чем отличается интеграция через общую БД от интеграции через API и почему первое считается антипаттерном?'),
('LEGACY_INTEGRATION', 'SENIOR', 'Что такое паттерн Strangler Fig и как он помогает постепенно заменять legacy-систему?'),
('LEGACY_INTEGRATION', 'SENIOR', 'Зачем нужен anti-corruption layer при интеграции с устаревшей системой?'),
('LEGACY_INTEGRATION', 'SENIOR', 'Какие подходы к миграции данных из legacy-БД вы знаете и в чём их риски?'),
('LEGACY_INTEGRATION', 'LEAD', 'Как организовать постепенный перенос трафика на новый сервис без простоя?'),
('LEGACY_INTEGRATION', 'LEAD', 'Какие версии API стоит поддерживать одновременно и как со временем выводить старые из эксплуатации?');
